name: CI - Type Checking
on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - main
      - dev
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install astro type checker
        run: npm i @astrojs/check typescript
      - name: Run type checking
        run: npm run check
