name: Astro CI
env:
    NODE_VERSION: "22"
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main]
jobs:
    type-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Run type checking
              run: npm run check
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Check for outdated dependencies
              run: npm outdated || true
