name: Astro CI

# Node version based on your typescript dependency
env:
  NODE_VERSION: '18'

on:
  push:
    branches: [ main, dev, 'feature/**', 'feat/**' ]  # Checks pushes to main, dev, and feature branches
  pull_request:
    branches: [ main ]  # Checks PRs targeting main branch

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run type checking
        run: npm run check

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check for outdated dependencies
        run: npm outdated || true